#!/usr/bin/env python3

from pathlib import Path
import os, sys, venv

def main():
    context = Path(__file__).resolve().parent
    venvpath = str(context / 'venv')
    installflag = context / '.install'
    if installflag.exists():
        venv.create(venvpath, with_pip = True)
        installflag.unlink()
    os.environ['MINICONDA3_HOME'] = venvpath
    projects = context / 'projects'
    pyvendir = projects / 'pyven'
    PATH = os.environ.get('PATH')
    # Prepend to use our pyven if system already has it:
    os.environ['PATH'] = str(pyvendir) if PATH is None else "%s%s%s" % (pyvendir, os.pathsep, PATH)
    argv = [str(projects / 'Concern' / 'Concern.py')] + sys.argv[1:]
    os.execv(argv[0], argv)

if '__main__' == __name__:
    main()
