#!/usr/bin/env python3

from pathlib import Path
import os, sys, venv, subprocess

def main():
    context = Path(__file__).resolve().parent
    venvpath = context / 'venv'
    requirementspath = context / '.requirements.txt'
    if requirementspath.exists():
        venv.create(str(venvpath), with_pip = True)
        subprocess.check_call([str(venvpath / 'bin' / 'pip'), 'install', '-r', str(requirementspath)])
        requirementspath.unlink()
    os.environ['MINICONDA3_HOME'] = str(venvpath)
    projects = context / 'projects'
    pyvendir = projects / 'pyven'
    PATH = os.environ.get('PATH')
    # Prepend to use our pyven if system already has it:
    os.environ['PATH'] = str(pyvendir) if PATH is None else "%s%s%s" % (pyvendir, os.pathsep, PATH)
    argv = [str(projects / 'Concern' / 'Concern.py')] + sys.argv[1:]
    os.execv(argv[0], argv)

if '__main__' == __name__:
    main()
