#!/bin/sh

stderr() {
    echo "$@" >&2
}

sigterm() {
    stderr Caught SIGTERM, exit normally.
    exit
}

trap sigterm TERM

stderr Sleeping until SIGTERM.

while true; do sleep 5 & wait $!; done # Foreground sleep would delay signal.
